services:
  mongodb:
    image: mongo:6
    container_name: mongodb_filmflix
    restart: unless-stopped
    volumes:
      - mongodb_data:/data/db

  backend:
    image: whodeepaksoni/filmflix-api:latest
    container_name: backend_filmflix
    restart: unless-stopped
    expose:
      - "5000"
    depends_on:
      - mongodb
    environment:
      PORT: 5000
      MONGO_URL: mongodb://mongodb:27017/filmflix
      SECRET_KEY: ${JWT_SECRET}

  admin:
    image: whodeepaksoni/filmflix-admin:latest
    container_name: admin_filmflix
    restart: unless-stopped
    expose:
      - "3000"
    depends_on:
      - backend


volumes:
  mongodb_data: