name: FilmFlix CI

'on':
  push:
    branches:
      - main
      - dev

  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Build Backend Image
        run: docker build -t filmflix-backend .

      - name: Build Admin Image
        run: docker build -t filmflix-admin ./admin

      - name: Scan Backend Image
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: filmflix-backend
          format: table
          exit-code: '0'
          ignore-unfixed: true
          severity: HIGH,CRITICAL